language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: build
  on:
    branch: source